### ISSUE TITLE
Visual and Usability Improvement

### ISSUE THREAD

**Issue by Israel-Laguan** [JuanPabloGil/Articles-Web-App#6]
First of all great work @JuanPabloGil ! 

- When you put Priority you can put as default, like in 2

- In home when there are no articles footer shows incorrectly, like in the middle
![image](https://user-images.githubusercontent.com/36519478/75358639-37e4fa00-5881-11ea-8510-973ea25e0551.png)

-- Maybe add a "read more" link to see the article
![image](https://user-images.githubusercontent.com/36519478/75359576-978fd500-5882-11ea-9b11-172436445bff.png)

**Comment by JuanPabloGil** [comment]
Fixed
